language: node_js
node_js:
  - "0.10"
before_script:
  - cp "modules/config.example.js" "modules/config.js"
notifications:
  irc:
    channels:
      - "irc.esper.net#spongy"
    skip_join: true
services:
  - redis-server